name: m_lseed_depl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Verify Commit Message
      uses: wagoid/commitlint-github-action@v3

    - name: Build the docker image
      run: docker-compose up -d
